<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Aspire.OllamaSharp" Version="13.3.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.8" />
    <PackageReference Include="Microsoft.SemanticKernel" Version="1.77.0" />
    <PackageReference Include="Microsoft.SemanticKernel.Abstractions" Version="1.77.0" />
    <PackageReference Include="Microsoft.SemanticKernel.Agents.Core" Version="1.77.0" />
    <PackageReference Include="Microsoft.SemanticKernel.Agents.Orchestration" Version="1.77.0-preview" />
    <PackageReference Include="Microsoft.SemanticKernel.Agents.Runtime.InProcess" Version="1.77.0-preview" />
    <PackageReference Include="Microsoft.SemanticKernel.Connectors.Ollama" Version="1.77.0-alpha" />
    <PackageReference Include="Microsoft.SemanticKernel.Core" Version="1.77.0" />
    <PackageReference Include="Microsoft.SemanticKernel.Experimental.Orchestration.Flow" Version="1.77.0-alpha" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\FinanceTracker.Data\FinanceTracker.Data.csproj" />
    <ProjectReference Include="..\FinanceTracker.Services\FinanceTracker.Services.csproj" />
    <ProjectReference Include="..\FinanceTracker.Shared.Setup\FinanceTracker.Shared.Setup.csproj" />
  </ItemGroup>

</Project>
