using System.Text;
using FinanceTracker.Generated.Helpers;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace FinanceTracker.Generated.Enums;

[Generator]
public class InjectionCategoryTypeEnumGenerator : IIncrementalGenerator
{
    private const string EnumSourceCode = $@"// <auto-generated/>

namespace {SourceGeneratorConstants.GeneratedNamespace}.Enums
{{
    public enum {SourceGeneratorConstants.InjectionCategoryEnumName}
    {{
        Service,
        Validator,
    }}
}}";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(ctx => ctx.AddSource(
            $"{SourceGeneratorConstants.InjectionCategoryEnumName}Enum.g.cs",
            SourceText.From(EnumSourceCode, Encoding.UTF8)));
    }
}