using System.Text;
using FinanceTracker.Generated.Helpers;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace FinanceTracker.Generated.Attributes;

[Generator]
public class InjectionCategoryAttributeGenerator : IIncrementalGenerator
{
    private const string AttributeSourceCode = $$"""
                                                 // <auto-generated/>
                                                 using FinanceTracker.Generated.Enums;
                                                 namespace {{SourceGeneratorConstants.GeneratedNamespace}}.Attributes
                                                 {
                                                     [System.AttributeUsage(System.AttributeTargets.Class)]
                                                     public class {{SourceGeneratorConstants.InjectionCategoryAttributeName}}({{SourceGeneratorConstants.InjectionCategoryEnumName}} Category) : System.Attribute
                                                     {
                                                     }
                                                 }
                                                 """;

    public void Initialize(IncrementalGeneratorInitializationContext context) =>
        context.RegisterPostInitializationOutput(ctx => ctx.AddSource(
            $"{SourceGeneratorConstants.InjectionCategoryAttributeName}.g.cs",
            SourceText.From(AttributeSourceCode, Encoding.UTF8)));
}
