using System.Text;
using FinanceTracker.Generated.Helpers;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace FinanceTracker.Generated.Attributes;

[Generator]
public class TransientAttributeGenerator : IIncrementalGenerator
{
    private const string AttributeSourceCode = $@"// <auto-generated/>

namespace {SourceGeneratorConstants.GeneratedNamespace}
{{
    [System.AttributeUsage(System.AttributeTargets.Class)]
    public class {SourceGeneratorConstants.TransientAttributeName}<TServiceInterface> : System.Attribute
    {{
    }}
}}";

    public void Initialize(IncrementalGeneratorInitializationContext context) =>
        context.RegisterPostInitializationOutput(ctx => ctx.AddSource(
            $"{SourceGeneratorConstants.TransientAttributeName}.g.cs",
            SourceText.From(AttributeSourceCode, Encoding.UTF8)));
}
